package inventory

import "time"

func Demo() *Inventory {
	return &Inventory{
		Tools: []ToolInfo{
			{ID: "claude", Name: "Claude Code", Installed: true, Version: "2.1.122 (Claude Code)", BinaryPath: "/usr/local/bin/claude", ConfigDir: "~/.claude", DataDir: "~/.claude/projects"},
			{ID: "codex", Name: "Codex CLI", Installed: true, Version: "codex-cli 0.125.0", BinaryPath: "/usr/local/bin/codex", ConfigDir: "~/.codex", DataDir: "~/.codex"},
			{ID: "copilot", Name: "Copilot CLI", Installed: true, Version: "1.0.5", BinaryPath: "/usr/local/bin/github-copilot", ConfigDir: "~/.copilot", DataDir: "~/.copilot/session-state"},
			{ID: "gemini", Name: "Gemini CLI", Installed: true, Version: "0.39.1", BinaryPath: "/usr/local/bin/gemini", ConfigDir: "~/.gemini", DataDir: "~/.gemini/tmp"},
			{ID: "opencode", Name: "OpenCode", Installed: true, ConfigDir: "~/.config/opencode", DataDir: "~/.local/share/opencode"},
			{ID: "cursor-ide", Name: "Cursor (IDE)", Installed: true, Version: "3.1.15", BinaryPath: "/usr/bin/cursor", ConfigDir: "~/.config/Cursor", DataDir: "~/.config/Cursor/User/globalStorage"},
			{ID: "antigravity", Name: "Antigravity", Installed: false},
			{ID: "goose", Name: "Goose", Installed: true, Version: "1.0.5", BinaryPath: "/usr/local/bin/goose", ConfigDir: "~/.config/goose"},
			{ID: "aider", Name: "Aider", Installed: false},
			{ID: "amp", Name: "Amp", Installed: false},
			{ID: "devin", Name: "Devin", Installed: false},
			{ID: "amazonq", Name: "Amazon Q Developer", Installed: false},
			{ID: "windsurf", Name: "Windsurf", Installed: false},
		},
		Models: []ModelUsage{
			{Model: "claude-opus-4-6", Provider: "claude", SessionCount: 42, LastUsed: time.Now().Add(-12 * time.Minute).Format(time.RFC3339)},
			{Model: "claude-sonnet-4-6", Provider: "claude", SessionCount: 28, LastUsed: time.Now().Add(-2 * time.Hour).Format(time.RFC3339)},
			{Model: "openai/gpt-5.4", Provider: "codex", SessionCount: 19, LastUsed: time.Now().Add(-45 * time.Minute).Format(time.RFC3339)},
			{Model: "gemini-3-pro", Provider: "gemini", SessionCount: 12, LastUsed: time.Now().Add(-4 * time.Hour).Format(time.RFC3339)},
			{Model: "gemini-3-flash", Provider: "gemini", SessionCount: 8, LastUsed: time.Now().Add(-24 * time.Hour).Format(time.RFC3339)},
			{Model: "gpt-5-mini", Provider: "copilot", SessionCount: 6, LastUsed: time.Now().Add(-3 * time.Hour).Format(time.RFC3339)},
			{Model: "llamacpp/qwen-3.6", Provider: "opencode", SessionCount: 4, LastUsed: time.Now().Add(-6 * time.Hour).Format(time.RFC3339)},
			{Model: "qwen-3.6-moe", Provider: "remote-agent", SessionCount: 2, LastUsed: time.Now().Add(-20 * time.Minute).Format(time.RFC3339)},
		},
		MCPServers: []MCPServer{
			{Name: "postgres", Command: "npx", Args: []string{"-y", "@modelcontextprotocol/server-postgres"}, Source: "claude-global", SourcePath: "~/.claude/settings.json", Scope: "global"},
			{Name: "github", Command: "npx", Args: []string{"-y", "@modelcontextprotocol/server-github"}, Source: "claude-global", SourcePath: "~/.claude/settings.json", Scope: "global"},
			{Name: "filesystem", Command: "npx", Args: []string{"-y", "@modelcontextprotocol/server-filesystem", "/home/user/Projects"}, Source: "claude-project", SourcePath: "~/.claude/projects/-home-user-Projects-web-dashboard/settings.json", Scope: "~/Projects/web-dashboard"},
			{Name: "stripe-agent", URL: "https://mcp.stripe.com", Source: "project", SourcePath: "~/Projects/payment-service/.claude/settings.local.json", Scope: "~/Projects/payment-service"},
			{Name: "sentry", Command: "npx", Args: []string{"-y", "@sentry/mcp-server"}, Source: "cursor", SourcePath: "~/.cursor/mcp.json", Scope: "global"},
			{Name: "linear", URL: "https://mcp.linear.app", Source: "claude-global", SourcePath: "~/.claude/settings.json", Scope: "global"},
			{Name: "datadog", Command: "datadog-mcp", Source: "windsurf", SourcePath: "~/.codeium/windsurf/mcp_config.json", Scope: "global"},
			{Name: "chrome-devtools", Source: "claude-plugin", SourcePath: "~/.claude/plugins/installed_plugins.json", Scope: "global"},
		},
		InstructionFiles: []InstructionFile{
			{Type: "CLAUDE.md", Path: "~/Projects/web-dashboard/CLAUDE.md", ProjectPath: "~/Projects/web-dashboard", ProjectName: "web-dashboard", SizeBytes: 4280, Modified: time.Now().Add(-48 * time.Hour).Format(time.RFC3339)},
			{Type: "CLAUDE.md", Path: "~/Projects/payment-service/CLAUDE.md", ProjectPath: "~/Projects/payment-service", ProjectName: "payment-service", SizeBytes: 6150, Modified: time.Now().Add(-72 * time.Hour).Format(time.RFC3339)},
			{Type: "CLAUDE.md", Path: "~/Projects/auth-service/CLAUDE.md", ProjectPath: "~/Projects/auth-service", ProjectName: "auth-service", SizeBytes: 2890, Modified: time.Now().Add(-120 * time.Hour).Format(time.RFC3339)},
			{Type: ".cursorrules", Path: "~/Projects/mobile-app/.cursorrules", ProjectPath: "~/Projects/mobile-app", ProjectName: "mobile-app", SizeBytes: 1240, Modified: time.Now().Add(-168 * time.Hour).Format(time.RFC3339)},
			{Type: "cursor-rules", Path: "~/Projects/mobile-app/.cursor/rules/react-native.mdc", ProjectPath: "~/Projects/mobile-app", ProjectName: "mobile-app", SizeBytes: 890, Modified: time.Now().Add(-96 * time.Hour).Format(time.RFC3339)},
			{Type: "cursor-rules", Path: "~/Projects/mobile-app/.cursor/rules/testing.mdc", ProjectPath: "~/Projects/mobile-app", ProjectName: "mobile-app", SizeBytes: 560, Modified: time.Now().Add(-96 * time.Hour).Format(time.RFC3339)},
			{Type: "GEMINI.md", Path: "~/Projects/doc-generator/GEMINI.md", ProjectPath: "~/Projects/doc-generator", ProjectName: "doc-generator", SizeBytes: 3400, Modified: time.Now().Add(-240 * time.Hour).Format(time.RFC3339)},
			{Type: "copilot-instructions.md", Path: "~/Projects/file-encryptor/.github/copilot-instructions.md", ProjectPath: "~/Projects/file-encryptor", ProjectName: "file-encryptor", SizeBytes: 1680, Modified: time.Now().Add(-336 * time.Hour).Format(time.RFC3339)},
			{Type: "AGENTS.md", Path: "~/Projects/cloud-infra/AGENTS.md", ProjectPath: "~/Projects/cloud-infra", ProjectName: "cloud-infra", SizeBytes: 5210, Modified: time.Now().Add(-96 * time.Hour).Format(time.RFC3339)},
			{Type: ".goosehints", Path: "~/Projects/home-automation/.goosehints", ProjectPath: "~/Projects/home-automation", ProjectName: "home-automation", SizeBytes: 780, Modified: time.Now().Add(-480 * time.Hour).Format(time.RFC3339)},
			{Type: ".aider.conf.yml", Path: "~/Projects/static-site/.aider.conf.yml", ProjectPath: "~/Projects/static-site", ProjectName: "static-site", SizeBytes: 420, Modified: time.Now().Add(-720 * time.Hour).Format(time.RFC3339)},
			{Type: "claude-agents", Path: "~/Projects/recommendation-engine/.claude/agents/embedding-specialist.md", ProjectPath: "~/Projects/recommendation-engine", ProjectName: "recommendation-engine", SizeBytes: 2100, Modified: time.Now().Add(-168 * time.Hour).Format(time.RFC3339)},
		},
		Skills: []Skill{
			{Name: "deploy", Type: "command", Source: "claude-global", Path: "~/.claude/commands/deploy.md"},
			{Name: "review", Type: "command", Source: "claude-global", Path: "~/.claude/commands/review.md"},
			{Name: "test-suite", Type: "command", Source: "project:payment-service", Path: "~/Projects/payment-service/.claude/commands/test-suite.md"},
			{Name: "db-migrate", Type: "command", Source: "project:payment-service", Path: "~/Projects/payment-service/.claude/commands/db-migrate.md"},
			{Name: "chrome-devtools-mcp", Type: "plugin", Source: "claude-plugin", Path: "~/.claude/plugins/installed_plugins.json"},
			{Name: "generate-diagrams", Type: "skill", Source: "project:doc-generator", Path: "~/Projects/doc-generator/SKILLS/generate-diagrams.md"},
			{Name: "review-architecture", Type: "skill", Source: "project:cloud-infra", Path: "~/Projects/cloud-infra/SKILLS/review-architecture.md"},
		},
		Memories: []MemoryFile{
			{Name: "user-profile", Description: "Senior engineer, prefers concise responses, Go and TypeScript focus", MemoryType: "user", Path: "~/.claude/projects/-home-user-Projects-web-dashboard/memory/user_profile.md", ProjectPath: "~/Projects/web-dashboard", ProjectName: "web-dashboard", SizeBytes: 480, Modified: time.Now().Add(-14 * 24 * time.Hour).Format(time.RFC3339)},
			{Name: "no-orm", Description: "Always use raw SQL with sqlc, never ORMs — burned by GORM migration bugs", MemoryType: "feedback", Path: "~/.claude/projects/-home-user-Projects-payment-service/memory/feedback_no_orm.md", ProjectPath: "~/Projects/payment-service", ProjectName: "payment-service", SizeBytes: 320, Modified: time.Now().Add(-21 * 24 * time.Hour).Format(time.RFC3339)},
			{Name: "stripe-v2-migration", Description: "Migrating from Stripe API v1 to v2, deadline June 15", MemoryType: "project", Path: "~/.claude/projects/-home-user-Projects-payment-service/memory/project_stripe_v2.md", ProjectPath: "~/Projects/payment-service", ProjectName: "payment-service", SizeBytes: 890, Modified: time.Now().Add(-7 * 24 * time.Hour).Format(time.RFC3339)},
			{Name: "oncall-dashboard", Description: "Grafana board at grafana.internal/d/api-latency for oncall", MemoryType: "reference", Path: "~/.claude/projects/-home-user-Projects-web-dashboard/memory/reference_grafana.md", ProjectPath: "~/Projects/web-dashboard", ProjectName: "web-dashboard", SizeBytes: 210, Modified: time.Now().Add(-30 * 24 * time.Hour).Format(time.RFC3339)},
			{Name: "prefer-single-pr", Description: "User prefers bundled PRs over many small ones for refactors", MemoryType: "feedback", Path: "~/.claude/projects/-home-user-Projects-auth-service/memory/feedback_single_pr.md", ProjectPath: "~/Projects/auth-service", ProjectName: "auth-service", SizeBytes: 280, Modified: time.Now().Add(-45 * 24 * time.Hour).Format(time.RFC3339)},
			{Name: "k8s-context", Description: "Staging cluster is 'eks-staging-v2', not the old 'eks-staging'", MemoryType: "project", Path: "~/.claude/projects/-home-user-Projects-cloud-infra/memory/project_k8s.md", ProjectPath: "~/Projects/cloud-infra", ProjectName: "cloud-infra", SizeBytes: 410, Modified: time.Now().Add(-10 * 24 * time.Hour).Format(time.RFC3339)},
			{Name: "linear-project", Description: "Bugs tracked in Linear project INGEST, feature work in PLATFORM", MemoryType: "reference", Path: "~/.claude/projects/-home-user-Projects-event-platform/memory/reference_linear.md", ProjectPath: "~/Projects/event-platform", ProjectName: "event-platform", SizeBytes: 190, Modified: time.Now().Add(-60 * 24 * time.Hour).Format(time.RFC3339)},
			{Name: "no-comments", Description: "Don't add comments unless explaining a non-obvious 'why'", MemoryType: "feedback", Path: "~/.claude/projects/-home-user-Projects-recommendation-engine/memory/feedback_no_comments.md", ProjectPath: "~/Projects/recommendation-engine", ProjectName: "recommendation-engine", SizeBytes: 350, Modified: time.Now().Add(-35 * 24 * time.Hour).Format(time.RFC3339)},
		},
		IDEExtensions: []IDEExtension{
			{ID: "github.copilot", Name: "GitHub Copilot", Version: "1.276.0", Publisher: "GitHub", IDE: "VS Code", IDEID: "vscode", Description: "Your AI pair programmer", Installed: time.Now().Add(-180 * 24 * time.Hour).Format(time.RFC3339)},
			{ID: "github.copilot-chat", Name: "GitHub Copilot Chat", Version: "0.42.3", Publisher: "GitHub", IDE: "VS Code", IDEID: "vscode", Description: "AI chat features powered by Copilot", Installed: time.Now().Add(-150 * 24 * time.Hour).Format(time.RFC3339)},
			{ID: "continue.continue", Name: "Continue", Version: "1.2.22", Publisher: "Continue", IDE: "VS Code", IDEID: "vscode", Description: "The leading open-source AI code agent", Installed: time.Now().Add(-60 * 24 * time.Hour).Format(time.RFC3339)},
			{ID: "saoudrizwan.claude-dev", Name: "Cline", Version: "3.14.1", Publisher: "saoudrizwan", IDE: "VS Code", IDEID: "vscode", Description: "Autonomous coding agent right in your IDE", Installed: time.Now().Add(-45 * 24 * time.Hour).Format(time.RFC3339)},
			{ID: "sourcegraph.cody-ai", Name: "Cody AI", Version: "2.1.0", Publisher: "Sourcegraph", IDE: "VS Code", IDEID: "vscode", Description: "AI coding assistant by Sourcegraph", Installed: time.Now().Add(-90 * 24 * time.Hour).Format(time.RFC3339)},
			{ID: "tabnine.tabnine-vscode", Name: "Tabnine", Version: "4.18.0", Publisher: "Tabnine", IDE: "VS Code", IDEID: "vscode", Description: "AI code completions", Installed: time.Now().Add(-200 * 24 * time.Hour).Format(time.RFC3339)},
			{ID: "github.copilot", Name: "GitHub Copilot", Version: "1.276.0", Publisher: "GitHub", IDE: "Cursor", IDEID: "cursor", Description: "Your AI pair programmer", Installed: time.Now().Add(-30 * 24 * time.Hour).Format(time.RFC3339)},
			{ID: "rooveterinaryinc.roo-cline", Name: "Roo Code", Version: "3.8.5", Publisher: "RooVeterinaryInc", IDE: "Cursor", IDEID: "cursor", Description: "AI-powered coding assistant", Installed: time.Now().Add(-20 * 24 * time.Hour).Format(time.RFC3339)},
		},
		SensitiveFiles: []SensitiveFile{
			{Path: "~/Projects/payment-service/.env", Name: ".env", ProjectName: "payment-service", Risk: "Environment variables — may contain API keys, database credentials, or secrets"},
			{Path: "~/Projects/payment-service/.env.production", Name: ".env.production", ProjectName: "payment-service", Risk: "Production environment — likely contains live credentials"},
			{Path: "~/Projects/web-dashboard/.env.local", Name: ".env.local", ProjectName: "web-dashboard", Risk: "Local environment overrides — often contains secrets not in version control"},
			{Path: "~/Projects/cloud-infra/credentials.json", Name: "credentials.json", ProjectName: "cloud-infra", Risk: "Credentials file — may contain OAuth tokens or service account keys"},
			{Path: "~/Projects/cloud-infra/deploy-key.pem", Name: "deploy-key.pem", ProjectName: "cloud-infra", Risk: "PEM certificate/key — may contain private keys"},
			{Path: "~/Projects/serving-api/.env", Name: ".env", ProjectName: "serving-api", Risk: "Environment variables — may contain API keys, database credentials, or secrets"},
		},
		ScanLog: []ScanEntry{
			{Path: "~/.claude/settings.json", Type: "mcp-config", Found: true},
			{Path: "~/.claude.json", Type: "mcp-config", Found: false},
			{Path: "~/.claude/plugins/installed_plugins.json", Type: "mcp-config", Found: true},
			{Path: "~/.cursor/mcp.json", Type: "mcp-config", Found: true},
			{Path: "~/.codeium/windsurf/mcp_config.json", Type: "mcp-config", Found: true},
			{Path: "~/.gemini/settings.json", Type: "mcp-config", Found: false},
			{Path: "~/.copilot/mcp-config.json", Type: "mcp-config", Found: false},
			{Path: "~/.config/goose/config.yaml", Type: "mcp-config", Found: false},
			{Path: "~/.claude/CLAUDE.md", Type: "instruction-file", Found: false},
			{Path: "~/.gemini/GEMINI.md", Type: "instruction-file", Found: false},
			{Path: "~/Projects/web-dashboard/CLAUDE.md", Type: "instruction-file", Found: true},
			{Path: "~/Projects/web-dashboard/.cursorrules", Type: "instruction-file", Found: false},
			{Path: "~/Projects/web-dashboard/.github/copilot-instructions.md", Type: "instruction-file", Found: false},
			{Path: "~/Projects/payment-service/CLAUDE.md", Type: "instruction-file", Found: true},
			{Path: "~/Projects/payment-service/.cursorrules", Type: "instruction-file", Found: false},
			{Path: "~/Projects/mobile-app/.cursorrules", Type: "instruction-file", Found: true},
			{Path: "~/Projects/mobile-app/.cursor/rules", Type: "rules-dir", Found: true},
			{Path: "~/Projects/doc-generator/GEMINI.md", Type: "instruction-file", Found: true},
			{Path: "~/Projects/cloud-infra/AGENTS.md", Type: "instruction-file", Found: true},
			{Path: "~/Projects/home-automation/.goosehints", Type: "instruction-file", Found: true},
			{Path: "~/.claude/commands", Type: "commands-dir", Found: true},
			{Path: "~/Projects/payment-service/.claude/commands", Type: "commands-dir", Found: true},
			{Path: "~/Projects/doc-generator/SKILLS", Type: "skills-dir", Found: true},
		},
		ProjectPaths: []string{
			"~/Projects/web-dashboard",
			"~/Projects/payment-service",
			"~/Projects/recommendation-engine",
			"~/Projects/auth-service",
			"~/Projects/cloud-infra",
			"~/Projects/event-platform",
			"~/Projects/mobile-app",
			"~/Projects/file-encryptor",
			"~/Projects/doc-generator",
			"~/Projects/email-classifier",
			"~/Projects/home-automation",
			"~/Projects/static-site",
		},
		ScanDurationMs: 3842,
		ScannedAt:      time.Now(),
	}
}
